### querying date
http://localhost:5290/api/orders?creationDate=2024-01-15

### by id
http://localhost:5290/api/orders/9bfe1f7f

### querying page
http://localhost:5290/api/orders?page=0

### mixed querying
http://localhost:5290/api/orders?userId=3d7503e1-b239-4017-a48e-46d0bbc7e5e8&queueId=0c54105c-8ace-45e7-888a-18cc78bf9281&status=New

### mark as paid
PATCH http://localhost:5290/api/orders/paid
Content-Type: application/json

{
  "id": "9bfe1f7f-6d6d-4341-9591-a767eef97ab6"
}

### mark as ready
PATCH http://localhost:5290/api/orders/ready
Content-Type: application/json

{
  "Id": "9bfe1f7f"
}
