version: '3.9'

services:
  vyazmatech-postgres:
    image: postgres:latest
    container_name: vyazmatech-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "6532:5432"
    restart: unless-stopped
    networks:
      - vyazmatech-network
  
  vyazmatech-seq:
    image: datalust/seq:latest
    container_name: vyazmatech-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    restart: unless-stopped
    networks:
      - vyazmatech-network

networks:
  vyazmatech-network:
    name: vyazmatech-network
    driver: bridge